package festival.srv.service;

import festival.srv.entity.Fruit;
import org.bson.Document;

import javax.enterprise.context.ApplicationScoped;
import javax.transaction.Transactional;
import java.util.List;
import java.util.stream.Collectors;

import static festival.srv.constant.MongoDbConstants.*;

@ApplicationScoped
public class FruitService extends Service<Fruit> {


	/**
	 * Create a fruit in the collection. The id is automatically generated by the database.
	 *
	 * @param fruit The fruit to create.
	 */
	@Transactional
	public void create(Fruit fruit){
		Document document = new Document()
				.append(NAME, fruit.getName())
				.append(DESCRIPTION, fruit.getDescription());

		super.create(document);
	}

	/**
	 * Get all fruits from the collection.
	 *
	 * @return The list of fruits.
	 */
	public List<Fruit> read(){
		return getDocumentList().stream().map(Fruit::new).collect(Collectors.toList());
	}

	/**
	 * Get a fruit from the collection.
	 *
	 * @param id The id of the fruit.
	 * @return The fruit.
	 */
	public Fruit read(String id){
		return new Fruit(getDocument(id));
	}

	@Override
	protected String getCollectionName() {
		return FRUITS_COLLECTION;
	}
}
